

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_container
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app  # Монтируем локальные файлы внутрь контейнера
      - /usr/src/app/node_modules  # Исключаем node_modules из локального монтирования
    environment:
      - NODE_ENV=production
